### ISSUE TITLE
Can't create a review for a POI

### ISSUE THREAD

**Issue by kevinzhao-tech** [321-PoM/findmy#101]
Getting this error when creating a new review for a poi
```
{"message":"Cannot read properties of undefined (reading 'poiId')"}
```

Using this request:
```
{"isDeleted":false,"poiId":8,"rating":4,"reliabilityScore":0,"userId":6}
```

**Comment by anjjunsu** [comment]
Fixed the obvious error.
<img width="683" alt="image" src="https://github.com/321-PoM/findmy/assets/90178502/0db8d6f8-f335-4d6e-bd17-6c9b2471869e">

**Comment by anjjunsu** [comment]
Please review @kevinzhao-tech , and close this issue :)

**Comment by muhan-alan-li** [comment]
There are other errors, may also be blocked by a faulty getUserReliabilityScore, will debug more later

**Comment by muhan-alan-li** [comment]
tested with postman and it works now -> right now its possible to create multiple duplicate reviews, which should have some logic in the backend to prevent this

**Comment by muhan-alan-li** [comment]
https://github.com/321-PoM/findmy/pull/119
