### ISSUE TITLE
Create friendship doesn't work

### ISSUE THREAD

**Issue by kevinzhao-tech** [321-PoM/findmy#102]
```
{"message":"\nInvalid `prisma.friendship.create()` invocation:\n\n{\n  data: {\n    userIdFrom: 6,\n    userIdTo: 1,\n    status: \"accepted\",\n+   friendshipId: Int\n  },\n  select: {\n    friendshipId: true\n  }\n}\n\nArgument `friendshipId` is missing."}
```

Do I need a friendshipID?

Here is the original req body:
```
{"userIdFrom":6,"userIdTo":1}
```

**Comment by anjjunsu** [comment]
Create friendship returns friendship ID, but there's no default value for ID, hence causing error. I guess. Updated the model and reflected to our server.

**Comment by anjjunsu** [comment]
Please review, and close the issue. @kevinzhao-tech  :)

**Comment by muhan-alan-li** [comment]
Tested with curl and this works now -> junsu and kevin are now friends with friendshipId = 1
