### ISSUE TITLE
Frontend handle denial of multiple reviews on single POI

### ISSUE THREAD

**Issue by kevinzhao-tech** [321-PoM/findmy#123]

**Comment by kevinzhao-tech** [comment]
Maybe this should be handled by the backend...

**Comment by kevinzhao-tech** [comment]
Otherwise a user can just restart the app

**Comment by muhan-alan-li** [comment]
![image](https://github.com/321-PoM/findmy/assets/85966696/bac0afb7-0467-41c6-9ef4-17c3402f51b3)

the create review ensures duplicate reviews can't be created
