### ISSUE TITLE
Await inside forloop

### ISSUE THREAD

**Issue by James-T-Ardian** [321-PoM/findmy#129]
Reference: https://github.com/321-PoM/findmy/blob/main/backend/services/userService.js#L105

It is not advisable to have awaits inside for loops as the async function will be resolved one by one rather than in parallel which is more efficient especially for resolving a large amount of concurrent async functions. The best practice to resolve multiple async functions in parallel is to use Promise.all (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)

**Comment by anjjunsu** [comment]
Hello @James-T-Ardian !

We have updated our `getUserReliabilityScore()`. Please see commit [24808ce](https://github.com/321-PoM/findmy/commit/24808cec3815d52dd975e1e0737321480c83ebeb).

If you have any other suggestions, please let us know! 

Thank you and please feel free to close this issue.

Thanks!

**Comment by James-T-Ardian** [comment]
LGTM! Thank you for the quick fix.
