### ISSUE TITLE
Centralized Error Handling

### ISSUE THREAD

**Issue by James-T-Ardian** [321-PoM/findmy#133]
Hello! I noticed that the error handling in the backend controllers are handled separately for each controller function. I believe it would follow best practice to reduce duplication and have some sort of centralized error handling to next() your controller errors into. Let me know whether this is something you can look into.

**Comment by anjjunsu** [comment]
Thank you for the great suggestion @James-T-Ardian !! 
Please check [PR](https://github.com/321-PoM/findmy/pull/134) when you have a time :)

Thank you!

**Comment by James-T-Ardian** [comment]
LGTM! Thank you for working on it :)
