### ISSUE TITLE
myPOI friendship restriction

### ISSUE THREAD

**Issue by kevinzhao-tech** [321-PoM/findmy#189]
Test if this works in frontend

**Comment by kevinzhao-tech** [comment]
Seems like there is a bug here. Using `pois/<user_id>` returns `restricted` description even if im the owner. Using `filteredPois/<long>/<lat>/<filter>/<radius>/<user_id>` doesn't restrict info

**Comment by muhan-alan-li** [comment]
tested list pois and get poi and both works now
