### ISSUE TITLE
Make a User Reliability Score calculation logic.

### ISSUE THREAD

**Issue by anjjunsu** [321-PoM/findmy#23]
Complete a function [`getUserReliabilityScore`](https://github.com/321-PoM/findmy/blob/main/backend/services/userService.js#L42).

Currently, it's getting below for you:
- Query ratings from public POIs created by user
- Query number of verified POIs reported by user

**Comment by muhan-alan-li** [comment]
[https://github.com/321-PoM/findmy/pulls](PR is up)
Please close this issue when PR is approved

**Comment by muhan-alan-li** [comment]
My idea for calculating RScore:

Consider user A, who we want to get the RScore of
For every Poi P that user A has left a review on:
1. Determine if the rating of review R left by user A is an outlier
2. Count the percentage of user A's reviews that are outliers
3. Let this be their reliability score.

**Comment by muhan-alan-li** [comment]
My implementation of RScore after the discussion

The function will iterate through every review made by a user
1.  For each of these reviews, a "safe zone" is defined as { mean - 1.5*stdev, mean + 1.5*stdev }
2.  We calculate the "distance" to the safe zone from the user's rating
3. We find the mean of the user's distance to the safe zone across all of their reviews

100 - mean of user's distance to safe zone = Rscore
