### ISSUE TITLE
Design friend module.

### ISSUE THREAD

**Issue by anjjunsu** [321-PoM/findmy#24]

**Comment by muhan-alan-li** [comment]
It looks like there is not way to have a bidirectional many-to-many relation: https://github.com/prisma/prisma/discussions/13214

So each friendship between two users will need to have 2 records in the friendship database to records it symmetrical: (user1 is a friend of user2), and (user2 is a friend of user1).

**Comment by muhan-alan-li** [comment]
This implementation feels a little janky, we could avoid this by having followers and following instead. This way the a user can follow someone without a follow back.
