### ISSUE TITLE
Design market transaction module.

### ISSUE THREAD

**Issue by anjjunsu** [321-PoM/findmy#26]
### Design market transaction module.

We may want to focus on:
- Logic for transaction
- Assignment -or- transfer of PoI ownership.

> **_Note:_**
> - We may need to update our model. 
>     - If so, please let @anjjunsu know and work together since we need to gradually update model from database schema to high-level classes in step-by-step.

Actual implementation will be done in following issue.

**Comment by muhan-alan-li** [comment]
This is now split into marketlsting, and transaction module -> both need to be implemented
