### ISSUE TITLE
Implement `getNearbyPoiWithFilter()` function.

### ISSUE THREAD

**Issue by anjjunsu** [321-PoM/findmy#27]
We need a function to get PoIs based on the user's location (If I'm understanding correctly).

- It should be 'get' request.
- And filter (which is param in request) should be:
    - Current lat
    - Current lng
    - PoI type 
        - Optional. If `None`, return all types of PoI
        - Can be combination of multiple PoI types (e.g. microwave -AND- washroom)
    - Within N meter from current user location

> **_Note:_**                 
> - Please update issue/spec if you want to.
> - Function name `getNearbyPoiWithFilter()` is not so good I guess...?

Thanks!

**Comment by jorido** [comment]
I'm going to limit the number of specified POI type filters to one. I don't see a strong use case of multiple OR'd POI types, and it adds unnecessary complications that can be avoided as of now.
