### ISSUE TITLE
get mapBux

### ISSUE THREAD

**Issue by kevinzhao-tech** [321-PoM/findmy#45]
create a post method that gives users a constant amount of mapBux (100 or smth) and adds it to their account. This will be a placeholder for buying mapBux.

**Comment by kevinzhao-tech** [comment]
The intention for this, is found on this page of the UI 
![image](https://github.com/321-PoM/findmy/assets/20373764/680a651e-edb7-4c67-b268-d2e680188fed)

**Comment by kevinzhao-tech** [comment]
I think it makes sense to associate mapBux to the User class and just update it as needed

**Comment by muhan-alan-li** [comment]
https://github.com/321-PoM/findmy/commit/fc8b90f6f836b1c0aaf8c45df427b05252c7666d

call updateUserBux with the following body, put userid in param
{
add: true/false for add/subtract
amount: amount
}
