### ISSUE TITLE
Implement unverified POI verification logic

### ISSUE THREAD

**Issue by jorido** [321-PoM/findmy#50]
Either backend or frontend, upto assignees decision...

**Comment by muhan-alan-li** [comment]
Scrapped for MVP, maybe implement for final product?

**Comment by anjjunsu** [comment]
@jorido @muhan-alan-li Do we still want this?

If not, please close the issue. Thanks!

**Comment by kevinzhao-tech** [comment]
Yea, we don't need this anymore. We have three complexities already
