### ISSUE TITLE
Adding friends

### ISSUE THREAD

**Issue by kevinzhao-tech** [321-PoM/findmy#54]
Need to have a method to add friends for a given user. Maybe a POST request to the `user/<id>` resource.

In the UI, a user would type in a friend's name and submit the form. Friends are "confirmed" if both friends have both added each other.
![image](https://github.com/321-PoM/findmy/assets/20373764/eef83ca8-38c3-4d98-bc3d-8c2f65c7c257)

**Comment by muhan-alan-li** [comment]
https://github.com/321-PoM/findmy/issues/60
