### ISSUE TITLE
Implement `Purchase PoI`

### ISSUE THREAD

**Issue by anjjunsu** [321-PoM/findmy#58]
Check user balance, 
update balance, 
change owner of poi,
...

**Comment by anjjunsu** [comment]
No we don't have this yet

**Comment by anjjunsu** [comment]
Estimate: Good ~2 hours

**Comment by muhan-alan-li** [comment]
do we want the last decision to be made by the buyer or the seller:
1. buyer sends offer -> seller accept or deny
2. seller puts up listing -> then buyer can choose to buy (seller does not get to deny)

I think the second option is what is referenced here:
Then we can create a transaction, then make 2 updateUserBux calls to update wallets, then make 1 call to updatePOI to update the owner. Then purchase POI just needs to be a wrapper for these 3 calls.
