### ISSUE TITLE
Friendship and Review model IDs are not autoincremented

### ISSUE THREAD

**Issue by jorido** [321-PoM/findmy#82]
Please refer to the other models in the schema which includes `@default(autoincrement())`. If there is a reason these models are not flagged similarly, please provide the reason and close the issue.

**Comment by muhan-alan-li** [comment]
I forgot to add the autoincrement.

@anjjunsu will I need to change the DB as well or can i just add `@default(autoincrement())` to the prisma schema

**Comment by muhan-alan-li** [comment]
Fields now have autoincrement
