### ISSUE TITLE
Marketplace API - Atomic operation for transaction

### ISSUE THREAD

**Issue by kevinzhao-tech** [321-PoM/findmy#88]
There is no API that completes a transaction atomically. Currently, a transaction would require the frontend to make all of the changes with separate requests. If at any point there is a failure in-between requests, reverts have to be made. It is very cumbersome to keep track of this on the frontend. Ideally there should be a request that can be made to the backend that does the following:
* Take a purchaser userid and marketlisting id
* Check and subtract mapbux from buyer and transfer to seller
* Transfer ownership
* Delete marketplace listing

**Comment by muhan-alan-li** [comment]
https://github.com/321-PoM/findmy/issues/58

Basically its one button on the app side? Click buy on the listing, the back end does everything atomically, and then deletes the listing upon completion?

**Comment by muhan-alan-li** [comment]
this will encapsulate 
- transferPoi
- updateUserBux
- deleteMarketListing

I will remove transferPoi because it is essentially being replaced by this atomic transaction API

**Comment by kevinzhao-tech** [comment]
> #58
> 
> Basically its one button on the app side? Click buy on the listing, the back end does everything atomically, and then deletes the listing upon completion?

Yea, it would be. To get an idea, the user would click purchase on this page
![image](https://github.com/321-PoM/findmy/assets/20373764/6b6730af-edee-4c76-9252-e42ef45aa29b)

**Comment by muhan-alan-li** [comment]
https://github.com/321-PoM/findmy/pull/98

**Comment by muhan-alan-li** [comment]
Tested with curl and done. 

> This is the current output on success:
> {"id":10,"latitude":49.18253833333333,"longitudes":-123.12182,"category":"myPOI","status":"verified","description":"mah > poi","ownerId":1,"rating":3,"reports":0,"isDeleted":false}
