### ISSUE TITLE
mapBux to int

### ISSUE THREAD

**Issue by kevinzhao-tech** [321-PoM/findmy#93]
It seems that there are some inconsistencies in the frontend and backend where mapBux is represented as an `int` and `float`. We should change all representations to `int` since there are alot of complications from `float`.
* Rounding errors
* Controlling number of decimals for precision
* etc.

From now on, if you make any new references to mapBux, use `int` so it will be easier to refactor later

**Comment by muhan-alan-li** [comment]
The backend should be free of mapBux floats

**Comment by anjjunsu** [comment]
Hello hello @muhan-alan-li .

Looks like it's done I guess?

**Comment by muhan-alan-li** [comment]
I didn't check the frontend but it is done for the backend @kevinzhao-tech @anjjunsu

**Comment by kevinzhao-tech** [comment]
> I didn't check the frontend but it is done for the backend @kevinzhao-tech @anjjunsu 

Thanks, I will check the front end

**Comment by anjjunsu** [comment]
@kevinzhao-tech @jorido Done...?

**Comment by kevinzhao-tech** [comment]
Frontend fixes https://github.com/321-PoM/findmy/commit/e18d5865caa3dfa0e98b1baa77f828b22d34b910
